[package]
name = "tower-sessions-core"
description = "Core types and traits for tower-sessions."
documentation.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
deletion-task = ["dep:tokio", "tokio/time"]
id-access = []

[dependencies]
time = "0.3.36"
http = { version = "1.1.0", optional = true }
base64 = "0.22.0"
futures = { version = "0.3.28", default-features = false, features = [
    "async-await",
] }
serde = { version = "1.0.189", features = ["derive"] }
either = "1.13"
tokio = { workspace = true, default-features = false, optional = true, features = [
    "time",
] }

[dev-dependencies]
tower-sessions = { workspace = true, features = [] }
tokio-test = "0.4.3"
tokio = { workspace = true, features = ["rt", "macros"] }
mockall = "0.13.0"
